### PR TITLE
ESLint & Upgrade deps

### PR DESCRIPTION
**Pull request by iiiii7d**
Upgraded discord.js to v14 and mongoose to v7.

Also tweaked some stuff that ESLint highlighted

Might have a few regressions here and there, but I can neither confirm nor deny

### CODE REVIEW

**Comment by bingoose0** [comment]
looks good to me

**Comment by bingoose0** [comment]
If this has been tested enough then feel free to merge it

**Comment by iiiii7d** [comment]
just so I cover all bases and nothing crashes and burns in prod what are all the functions that I should test? thanks :)

**Comment by bingoose0** [comment]
maybe stuff like town adding, elections, and obviously commands. up to you for how much you wanna test

**Comment by iiiii7d** [comment]
will test today. probs

**Comment by iiiii7d** [comment]
sorry for mess

**Comment by iiiii7d** [comment]
ill be redoing the upgrade

**Pull request closed without merging**
